import type { ZipContextSource, ZipEmployeeContext, ZipPresetContext } from "./contracts.ts";

export const ZIP_PRESETS: ZipPresetContext[] = [
  { id: "floor-care", sourceId: "preset:floor-care", name: "Interior floor care", purpose: "Clean assigned interior hard-floor areas safely and leave them ready for use.", steps: ["Confirm the assigned area before starting.", "Place safety signs before wet cleaning.", "Clean the assigned floor using the company-approved method.", "Inspect the area before reopening it."], safetyRules: ["Place wet-floor signs before cleaning.", "Do not mix cleaning chemicals unless the company procedure explicitly authorizes it."], evidence: ["Report completion to dispatch."], completionDefinition: "The assigned floor area is clean, safe, and reported complete to dispatch." },
  { id: "exterior-cleaning", sourceId: "preset:exterior-cleaning", name: "Exterior cleaning", purpose: "Clean the assigned exterior surface while protecting people, property, and access areas.", steps: ["Confirm the assigned surface and access area.", "Set up the work area safely.", "Complete only the assigned exterior cleaning.", "Inspect the surface and surrounding area before leaving."], safetyRules: ["Keep people clear of the active work area.", "Stop and contact dispatch if the assigned surface or access condition is unsafe."], evidence: ["Report completion to dispatch."], completionDefinition: "The assigned exterior surface is cleaned, the area is left safe, and completion is reported." },
  { id: "general-field-service", sourceId: "preset:general-field-service", name: "General field service", purpose: "Complete the specifically assigned field-service work without expanding scope.", steps: ["Confirm the assigned location and task.", "Complete only the approved work.", "Stop and contact dispatch if required facts or safe conditions are missing.", "Report completion."], safetyRules: ["Do not perform work outside the approved assignment.", "Stop and contact dispatch when a safety requirement is unclear."], evidence: ["Report completion to dispatch."], completionDefinition: "The approved work is complete and dispatch has been notified." }
];

export const phase1FixtureEmployee: ZipEmployeeContext = { id: "employee-demo", sourceId: "employee:employee-demo", displayName: "Jordan Rivera", role: "Field Technician", department: "Field Operations", authorizedJobTypes: ["floor-care", "general-field-service"], training: ["Wet-floor signage procedure"], preferredLanguage: "English", communicationDetail: "standard", responsibilities: ["Complete assigned field work and report blockers to dispatch."] };
export const phase1FixtureSource: ZipContextSource = { company: { sourceId: "company:phase1-demo", name: "ZIP Phase 1 Demo Company", policies: ["Do not expand work beyond the approved assignment.", "Stop and contact dispatch when required information or safe conditions are missing."] }, presets: ZIP_PRESETS, employees: [phase1FixtureEmployee] };
export function buildWorkspaceZipSource(companyName: string, employee: { id: string; name: string; role: string }): ZipContextSource { return { company: { sourceId: `company:${companyName.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "workspace"}`, name: companyName, policies: [] }, presets: ZIP_PRESETS, employees: [{ id: employee.id, sourceId: `employee:${employee.id}`, displayName: employee.name, role: employee.role, department: "", authorizedJobTypes: [], training: [], preferredLanguage: "English", communicationDetail: "standard", responsibilities: [] }] }; }
